blank_issues_enabled: false
contact_links:
  - name: RLNT Discord
    url: https://discord.com/invite/Q3qxws6
    about: Join the Discord to get help and support!
  - name: RLNT Organization
    url: https://github.com/RLNT
    about: Check out our organization on GitHub!
